version: "2.4"

services:
  bot:
    image: far4599/youtube-download-telegram-bot:latest
    restart: always
    mem_limit: 128m
    env_file:
      - .env
    volumes:
      - bot-sessions-volume:/app/sessions

volumes:
  bot-sessions-volume: